
# #system monitor
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    # - type: memory_free
    # - type: swap_use_percent
    - type: processor_use
   
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
 
- platform: command_line
  name: Database File Size
  command: "du -m /config/home-assistant_v2.db | cut -f1"
  unit_of_measurement: 'MB'
  value_template: '{{ value | int - 1 }}'

- platform: uptime

- platform: dht
  name: Living Room
  sensor: DHT11
  pin: 4
  monitored_conditions:
    - temperature
    - humidity
  scan_interval: 300

# - platform: command_line
#   name: wastecollection
#   command: "python3 /config/python_scripts/wastecollection.py"
#   scan_interval: 21600 # 6hrs

- platform: rest
  resource: !secret waste_collection_url
  name: wastecollection
  value_template: '{{ value_json }}'
  scan_interval: 21600 # 6hrs


- platform: rest
  name: wastecollection
  resource: !secret waste_collection_url
  json_attributes:
    - recyclingNextDate
    - organicNextDate
    - residualNextDate
    - AttachmentURL
  value_template: 'OK'
- platform: template
  sensors:
    next_recycling_collection:
      value_template: '{{ states.sensor.wastecollection.attributes["recyclingNextDate"] }}'
    next_rubbish_collection:
      value_template: '{{ states.sensor.wastecollection.attributes["residualNextDate"] }}'
    next_garden_collection:
      value_template: '{{ states.sensor.wastecollection.attributes["organicNextDate"] }}'
    wastecollection_pdf:
      value_template: '{{ states.sensor.wastecollection.attributes["AttachmentURL"] }}'

- platform: mqtt
  name: "Garage Temperature"
  state_topic: "garage/dht/status/temperature"
  unit_of_measurement: '°C'
  #value_template: "{{ value_json.temperature }}"
  #availability_topic: "garage/dht/status/"
  device_class: "temperature"

- platform: mqtt
  name: "Garage Humidity"
  state_topic: "garage/dht/status/humidity"
  unit_of_measurement: '%'
  #value_template: "{{ value_json.temperature }}"
  #availability_topic: "garage/dht/status/"
  device_class: "humidity"

# - platform: rest
#   name: Sourdough Temperature
#   unit_of_measurement: "°C"
#   resource: http://192.168.0.78/getTemp
#   scan_interval: 300

# - platform: rest
#   name: Sourdough Humidity
#   unit_of_measurement: "%"
#   resource: http://192.168.0.78/getHumidity
#   scan_interval: 300

# - platform: rest
#   name: Sourdough Heating Status
#   resource: http://192.168.0.78/getHeatStatus
#   scan_interval: 300

#https://home-assistant.io/components/sensor.cert_expiry/
# - platform: cert_expiry
#   host: !secret ssl_host
#   port: 8123
#   name: SSL Expiry1