
#system monitor
- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /
    - type: memory_use_percent
    # - type: memory_free
    # - type: swap_use_percent
    - type: processor_use
   
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
 
- platform: command_line
  name: Database File Size
  command: "du -m /config/home-assistant_v2.db | cut -f1"
  unit_of_measurement: 'MB'
  value_template: '{{ value | int - 1 }}'

- platform: dht
  name: TV Unit
  sensor: DHT11
  pin: 4
  monitored_conditions:
    - temperature
    - humidity
  scan_interval: 60

#https://home-assistant.io/components/sensor.cert_expiry/
- platform: cert_expiry
  host: !secret ssl_host
  port: 8123
  name: SSL Expiry