
# #system monitor
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    # - type: memory_free
    # - type: swap_use_percent
    - type: processor_use
   
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
 
- platform: command_line
  name: Database File Size
  command: "du -m /config/home-assistant_v2.db | cut -f1"
  unit_of_measurement: 'MB'
  value_template: '{{ value | int - 1 }}'

- platform: uptime

- platform: dht
  name: Living Room
  sensor: DHT11
  pin: 4
  monitored_conditions:
    - temperature
    - humidity
  scan_interval: 300

# - platform: command_line
#   name: wastecollection
#   command: "python3 /config/python_scripts/wastecollection.py"
#   scan_interval: 21600 # 6hrs

# - platform: rest
#   resource: !secret waste_collection_url
#   name: wastecollection
#   value_template: '{{ value_json }}'
#   scan_interval: 21600 # 6hrs


- platform: rest
  name: wastecollection
  resource: !secret waste_collection_url
  json_attributes:
    - recyclingNextDate
    - organicNextDate
    - residualNextDate
    - AttachmentURL
  value_template: 'OK'

- platform: template
  sensors:
    next_recycling_collection:
      value_template: '{{ states.sensor.wastecollection.attributes["recyclingNextDate"] }}'
    next_rubbish_collection:
      value_template: '{{ states.sensor.wastecollection.attributes["residualNextDate"] }}'
    next_garden_collection:
      value_template: '{{ states.sensor.wastecollection.attributes["organicNextDate"] }}'
    wastecollection_pdf:
      value_template: '{{ states.sensor.wastecollection.attributes["AttachmentURL"] }}'
    outside_temperature:
      value_template: '{{float(state_attr("weather.home", "temperature")) }}'
      unit_of_measurement: '°C'
      device_class: "temperature"
    outside_humidity:
      value_template: '{{float(state_attr("weather.home", "humidity")) }}'
      unit_of_measurement: '%'
      device_class: "humidity"
    bedroom_temperature:
      value_template: '{{float(state_attr("sensor.esp_a", "t")) }}'
      unit_of_measurement: '°C'
      device_class: "temperature"
    studio_temperature:
      value_template: '{{float(state_attr("sensor.esp_b", "t")) }}'
      unit_of_measurement: '°C'
      device_class: "temperature"
    conservatory_temperature:
      value_template: '{{float(state_attr("sensor.esp_c", "t")) }}'
      unit_of_measurement: '°C'
      device_class: "temperature"
    a_v:
      value_template: '{{float(state_attr("sensor.esp_a", "v")) }}'
      unit_of_measurement: 'v'
    b_v:
      value_template: '{{float(state_attr("sensor.esp_b", "v")) }}'
      unit_of_measurement: 'v'
    c_v:
      value_template: '{{float(state_attr("sensor.esp_c", "v")) }}'
      unit_of_measurement: 'v'
    a_w:
      value_template: '{{float(state_attr("sensor.esp_a", "w")) }}'
      unit_of_measurement: 's'
    b_w:
      value_template: '{{float(state_attr("sensor.esp_b", "w")) }}'
      unit_of_measurement: 's'
    c_w:
      value_template: '{{float(state_attr("sensor.esp_c", "w")) }}'
      unit_of_measurement: 's'
    a_ch:
      value_template: '{{float(state_attr("sensor.esp_a", "ch")) }}'
    b_ch:
      value_template: '{{float(state_attr("sensor.esp_b", "ch")) }}'
    c_ch:
      value_template: '{{float(state_attr("sensor.esp_c", "ch")) }}'

- platform: mqtt
  name: "Garage Temperature"
  state_topic: "garage/dht/status/temperature"
  unit_of_measurement: '°C'
  #availability_topic: "garage/dht/status/"
  device_class: "temperature"

- platform: mqtt
  name: "Garage Humidity"
  state_topic: "garage/dht/status/humidity"
  unit_of_measurement: '%'
  #availability_topic: "garage/dht/status/"
  device_class: "humidity"

- platform: mqtt
  name: "ESP A"
  state_topic: "esp/a/data"
  availability_topic: "esp/a/status"
  expire_after: 300
  payload_available: "online"
  payload_not_available: "disconnected"
  value_template: '{{ value_json }}'
  json_attributes_topic: "esp/a/data"

- platform: mqtt
  name: "ESP B"
  state_topic: "esp/b/data"
  availability_topic: "esp/b/status"
  expire_after: 300
  payload_available: "online"
  payload_not_available: "disconnected"
  value_template: '{{ value_json }}'
  json_attributes_topic: "esp/b/data"

- platform: mqtt
  name: "ESP C"
  state_topic: "esp/c/data"
  availability_topic: "esp/c/status"
  expire_after: 300
  payload_available: "online"
  payload_not_available: "disconnected"
  value_template: '{{ value_json.v }}'
  json_attributes_topic: "esp/c/data"

# - platform: rest
#   name: Sourdough Temperature
#   unit_of_measurement: "°C"
#   resource: http://192.168.0.78/getTemp
#   scan_interval: 300

# - platform: rest
#   name: Sourdough Humidity
#   unit_of_measurement: "%"
#   resource: http://192.168.0.78/getHumidity
#   scan_interval: 300

# - platform: rest
#   name: Sourdough Heating Status
#   resource: http://192.168.0.78/getHeatStatus
#   scan_interval: 300

#https://home-assistant.io/components/sensor.cert_expiry/
# - platform: cert_expiry
#   host: !secret ssl_host
#   port: 8123
#   name: SSL Expiry1